### ISSUE TITLE
Copy Photos only in Botchat

### ISSUE THREAD

**Issue by timgahmen** [devgaganin/Save-Restricted-Content-Bot-V2#28]
I set a destination channel in the Bot with
`setchat`

With Videos + Documents it works perfect. only if I try to copy Photos the bot only upload them in the "Botchat" not in the "setchat" (Channel)

(if I am the only one with this problem?)

and on this way thank you very much for this awesome bot

**Comment by devgaganin** [comment]
#fixed #Repo #updated ✨ 
Happy coding.... re deploy and use.

**Comment by timgahmen** [comment]
awesome! works now! 

thanks for this very fast and very good fix !

but better change this:
...
await gagan.send_file(target_chat_id, path, caption=caption)
`# await gagan.send_file(LOG_GROUP, path, caption=caption)`
...

back to:
...
await gagan.send_file(target_chat_id, path, caption=caption)
`await gagan.send_file(LOG_GROUP, path, caption=caption)`
...

then the "Log Group" also works again with Photos 😊

**Comment by devgaganin** [comment]
I already merged your commits
