### ISSUE TITLE
Contact 

### ISSUE THREAD

**Issue by timgahmen** [devgaganin/Save-Restricted-Content-Bot-V2#30]
Hello,

sorry that I write here, I try to contact you but:
- Telegram Channel (I can not answer in the channel, or see your contact accound)
- E-Mail is not existing anymore ?
- Website works, but the contacts options not ....
- linkedIn I not have :-/

If you like write me
- in TG: https://t.me/ContactTim_bot
- E-Mail: timgahmencoding@gmail.com

Thank you

**Comment by devgaganin** [comment]
Send me message at t.me/ttonehelpbot
