### ISSUE TITLE
file name got skip

### ISSUE THREAD

**Issue by bbrooks870** [devgaganin/Save-Restricted-Content-Bot-V2#34]
sir no names coming after downloading
![image](https://github.com/user-attachments/assets/6777be08-2c44-481b-9703-052d2e273b62)

this was original file
![image](https://github.com/user-attachments/assets/b97a0c8f-7388-4b30-96a3-15d45d6b1bf8)

**Comment by bbrooks870** [comment]
.mp4 file in file format , file name is not comming in Video caption 
as u can see

**Comment by devgaganin** [comment]
It is because video is converted to streamable format and original files was having no caption that's why not appeared in th files you extracted
