### ISSUE TITLE
Per I'd problem pls fix this 

### ISSUE THREAD

**Issue by hemendrasahu67** [devgaganin/Save-Restricted-Content-Bot-V2#39]
Failed to save: https://t.me/c/2229878424/1181

Error: Peer id invalid: -1002229878424

Kuch pvt channel ka video Nikal aata hai but kuch mai ye problem hota hai mostly jada tar yahi problem ho ri hai 100 mai se 10% Chanel ka video Nikal raha hai bas baki sab mai ye problem hai pls fix this issue

**Comment by devgaganin** [comment]
Re deploy
