### ISSUE TITLE
Got a issue in giving premium plans to the user

### ISSUE THREAD

**Issue by PiroLeader** [devgaganin/Save-Restricted-Content-Bot-V2#43]
**when i give premium access to a user to use "batch" command in v4 branch, the bot shows "Only 10 messages allowed in batch size... Purchase premium to fly".**

![2cb8](https://github.com/user-attachments/assets/eca29af8-bf76-4e4a-983e-787f84bca501)

**Comment by devgaganin** [comment]
You have to increase the value of batch in the repo let me do it in main repo thanks for letting it out...
