### ISSUE TITLE
Logout device

### ISSUE THREAD

**Issue by krackxor** [devgaganin/Save-Restricted-Content-Bot-V2#50]
Why am I logged out of the device when using /login

**Comment by alreadydea** [comment]
u have to first logout then login otherwise mongodb will be locked thats why

**Comment by krackxor** [comment]
> u have to first logout then login otherwise mongodb will be locked thats why

So I log in then log out and log in again then download the file?

**Comment by Sourabh23113** [comment]
What's difference between log_group id and channel_id

**Comment by krackxor** [comment]
> channel_id

Log group for dump file
Channel id for subscribe channel

**Comment by Sourabh23113** [comment]
In render, 'this action is not allowed' message comes while deploying.....what can be the reason

**Comment by iamrohitx** [comment]
Render par repo 
Action not allowed 
Plzz contact me  t.me/TGJokerX

**Comment by iamrohitx** [comment]
> In render, 'this action is not allowed' message comes while deploying.....what can be the reason

Yes bro same problem 
Contact me   

https://t.me/TGJokerX

**Comment by alreadydea** [comment]
fork and give star

**Comment by devgaganin** [comment]
@krackxor in which bot you were facing issue of logout ?

**Comment by krackxor** [comment]
> @krackxor in which bot you were facing issue of logout ?

V3 branch | Summer Release V2

**Comment by devgaganin** [comment]
Km

> > @krackxor in which bot you were facing issue of logout ?
> 
> V3 branch | Summer Release V2

Ok so make sure you are not logged in at many device and also in your bot there should be limit of logins on server where you are deploying so check that also
