### ISSUE TITLE
Reset option is not working properly.

### ISSUE THREAD

**Issue by PiroLeader** [devgaganin/Save-Restricted-Content-Bot-V2#52]
In settings option, reset only work in "remove words" option instead it should work on all the options present in settings. As usual, reset should make everything to default where we haven't set our "CHAT ID", "Rename Tag", "Caption", "Replace Words", "Remove Words". Logout option also not functioning in settings. 

One request from my side to add "/help" command so that use of "HELP2_TXT", "HELP_TXT" available in script.py.. As u mentioned to add pdf watermark imports to add in repo after u get 100+ followers in github. Hopefully u can do it ASAP.

Thank You

**Comment by devgaganin** [comment]
Hey @PiroLeader thanks for raising issue, I will check it out and fix the things and also do the things as promised for watermark functionalities...

**Comment by devgaganin** [comment]
Issues is fixed reset is now working
