### ISSUE TITLE
Not working on private channels

### ISSUE THREAD

**Issue by JK47-collab** [devgaganin/Save-Restricted-Content-Bot-V2#56]
Hi there and thanks for your amazing bot
There is only a issue that when I login to bot it’s not working for private chats. When there is no invite link for a channel or group and I’m member of that chat, this option(login) should work.

**Comment by devgaganin** [comment]
It may be topic enabled **group** so you have to modify the link a little bit.
remove extra parts 
Ex. 

https://t.me/125668666/5/12

you have to remove /5 as below

https://t.me/125668666/12
