### ISSUE TITLE
not working in group or channel directly 

### ISSUE THREAD

**Issue by DeV2135** [devgaganin/Save-Restricted-Content-Bot-V2#58]
@devgaganin @timgahmen 
![Screenshot_20241030-182046~2](https://github.com/user-attachments/assets/749803b2-9811-408a-bb1a-78c5b68eaed9)

When i try to use the bot direct into the channel and group.
I get following messages.
'Please purchase premium to do the task '
Because of this i need to extract the content to bot and manually set respective id to the bot

**Comment by devgaganin** [comment]
First authorise your I'd with command `/add YOUR_ID 1 year` This command must be sent from OwnerID account you filled in repo.
Note even you are you have to authorise yourself.

**Comment by DeV2135** [comment]
![Screenshot_20241101-161504](https://github.com/user-attachments/assets/fa34d128-2a4f-4ab4-85a1-4e31c074a1f4)

![Screenshot_20241101-161446](https://github.com/user-attachments/assets/e1fe63b6-afd8-4d03-9445-311e0c12b9cd)
Even after doing so i am unable to use respective features.
Let me know do u mean /login by authorising.
