### ISSUE TITLE
Solution please 

### ISSUE THREAD

**Issue by Ayus444** [devgaganin/Save-Restricted-Content-Bot-V2#60]
[
![Screenshot_20241115-235329](https://github.com/user-attachments/assets/432d185d-efba-41f5-8b43-7a92316d2fc6)
](url)

**Comment by devgaganin** [comment]
Make bot admin or initialize again

**Comment by Ayus444** [comment]
> Make bot admin or initialize again

Already an admin in my channel , getting same error again and again at /start command meanwhile other commands are working fine /start and /login are giving this output

**Comment by devgaganin** [comment]
Have you change the Pyrogram version ? If yes then use my edited one to fix the peer_id invalid and after deployment unadmin bot and make admin again sometimes glitch is there
