### ISSUE TITLE
V2 & V4 Branch Not Working 

### ISSUE THREAD

**Issue by Mahin321** [devgaganin/Save-Restricted-Content-Bot-V2#62]
I deployed this repo in koyeb. V3 Branch is deployed successfully  and working totally fine. v2 & v4 Branch is also deployed successfully without showing any error in logs But bot is not responding . I also tried with revoking token and creating new bot but not working . But v3 branch working with that same bot token.

When I deployed V3 branch :
![IMG_3964](https://github.com/user-attachments/assets/8a7a7cd0-2e3b-4835-8c10-dbfee2733e2c)

When I deployed V2 & V4 Branch :
![IMG_3962](https://github.com/user-attachments/assets/ee94cfec-b263-4798-be71-ac37c4fc998c)
![IMG_3965](https://github.com/user-attachments/assets/11054ae0-9a9d-4212-9517-e004542bdc05)
As you can see there is error in the logs. But bot is not responding.

**Comment by aajcodekrnahai** [comment]
bsdk v3 thik chal rha tu usi ko chala nah

**Comment by Mahin321** [comment]
> bsdk v3 thik chal rha tu usi ko chala nah

abe bsdk forced login use nhi krna chatha isliye hi v2/v4 branch use krna cha raha hu.

**Comment by devgaganin** [comment]
@Mahin321 I will see it why those are not working.
Thanks for raising issue
